models/Shop.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "shop".
 *
 * @property int $id
 * @property string $name
 * @property string $description
 *
 * @property ScheduleByDate[] $schedulesByDate
 * @property ScheduleByWeek[] $schedulesByWeek
 */
class Shop extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'shop';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['description'], 'string'],
            [['name'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'description' => Yii::t('app', 'Description'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSchedulesByDate()
    {
        return $this->hasMany(ScheduleByDate::className(), ['shop_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSchedulesByWeek()
    {
        return $this->hasMany(ScheduleByWeek::className(), ['shop_id' => 'id']);
    }

    /**
     * @param string $date
     * @return array
     */
    public function getScheduleByDate($date){
        $scheduleByDate = ScheduleByDate::find()->where([
            'shop_id'=>$this->id,
            'date'=>$date,
        ])->one();
        if ($scheduleByDate){
            return [
                'open_time'=>$scheduleByDate->open_time?Yii::$app->formatter->asTime($scheduleByDate->open_time):null,
                'close_time'=>$scheduleByDate->close_time?Yii::$app->formatter->asTime($scheduleByDate->close_time):null,
            ];
        }
        $scheduleByWeek = ScheduleByWeek::find()->where([
            'shop_id'=>$this->id
        ])->andWhere("day_of_week = IF(DAYOFWEEK(:date) = 1, 6, DAYOFWEEK(:date) - 2)", [":date"=>$date])
        ->one();
        if ($scheduleByWeek){
            return [
                'open_time'=>Yii::$app->formatter->asTime($scheduleByWeek->open_time),
                'close_time'=>Yii::$app->formatter->asTime($scheduleByWeek->close_time),
            ];
        }
        return [
            'open_time'=>null,
            'close_time'=>null
        ];
    }


    public function getSchedule($date = null)
    {
        $chedulesByWeek = $this->schedulesByWeek;
        $days = ScheduleByWeek::daysOfWeek();
        $schedule = [];
        foreach ($chedulesByWeek as $model){
            $schedule[$model->day_of_week] = [
                'day'=>$days[$model->day_of_week],
                'open_time' => Yii::$app->formatter->asTime($model->open_time),
                'close_time' => Yii::$app->formatter->asTime($model->close_time),
            ];
        }
        foreach ($days as $key=>$day){
            if (!array_key_exists($key, $schedule)){
                $schedule[$key] = [
                    'day'=>$day,
                    'open_time' => null,
                    'close_time' => null,
                ];
            }
        }
        ksort($schedule);
        $today = $this->getScheduleByDate(date("Y-m-d"));
        if ($date){
            $schedule_by_date = $this->getScheduleByDate($date);
            $schedule_by_date = [
                "$date"=>[
                    'day'=>"$date",
                    'open_time'=>$schedule_by_date['open_time'],
                    'close_time'=>$schedule_by_date['close_time'],
                ]
            ];
        }
        $today = [
            'today'=>[
                'day'=>'today',
                'open_time'=>$today['open_time'],
                'close_time'=>$today['close_time'],
            ],
        ];

        $schedule = $today + $schedule;

        if ($date)
            $schedule = $schedule_by_date + $schedule;

        return $schedule;
    }
}

controllers/ScheduleController.php
<?php

namespace app\controllers;

use app\base\Model;
use app\models\Shop;
use Yii;
use app\models\ScheduleByDate;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use yii\widgets\ActiveForm;

/**
 * ScheduleController implements the CRUD actions for ScheduleByDate model.
 */
class ScheduleController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * @param int $id
     * @return mixed
     * @throws NotFoundHttpException
     * @throws \yii\db\Exception
     */
    public function actionCreate($id)
    {
        $modelShop = $this->findShopModel($id);

        $schedulesByDate = Model::createMultiple(ScheduleByDate::class, [], 'shop_id', $modelShop->id);
        if (Model::loadMultiple($schedulesByDate, Yii::$app->request->post())) {
            // ajax validation
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ActiveForm::validateMultiple($schedulesByDate);
            }

            if (Model::validateMultiple($schedulesByDate)) {
                if (Model::saveMultiple($modelShop, $schedulesByDate))
                    return $this->redirect(['/shop/view', 'id' => $modelShop->id]);
            }
        }

        return $this->render('create', [
            'models' => (empty($schedulesByDate)) ? [new ScheduleByDate] : $schedulesByDate,
            'modelShop'=>$modelShop,
        ]);
    }

    /**
     * Updates an existing ScheduleByDate model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
			// ajax validation
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            }
			if ($model->save())
				return $this->redirect(['/shop/view', 'id' => $model->shop_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * @param int $id
     * @return \yii\web\Response
     * @throws NotFoundHttpException
     * @throws \Exception
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $shop_id = $model->shop_id;
        $model->delete();
        return $this->redirect(['/shop/view', 'id'=>$shop_id]);
    }

    /**
     * Finds the ScheduleByDate model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ScheduleByDate the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ScheduleByDate::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }

    /**
     * @param $id
     * @return Shop
     * @throws NotFoundHttpException
     */
    protected function findShopModel($id)
    {
        if (($model = Shop::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

controllers/ShopController.php
<?php

namespace app\controllers;

use app\base\Model;
use app\models\ScheduleByDateSearch;
use app\models\ScheduleByWeek;
use Yii;
use app\models\Shop;
use app\models\ShopSearch;
use yii\web\Response;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\widgets\ActiveForm;

/**
 * ShopController implements the CRUD actions for Shop model.
 */
class ShopController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Lists all Shop models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ShopSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'date'=>$searchModel->schedule_search,
        ]);
    }

    /**
     * Displays a single Shop model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $searchModel = new ScheduleByDateSearch($id);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('view', [
            'scheduleSearchModel' => $searchModel,
            'scheduleDataProvider' => $dataProvider,
            'model' => $model,
        ]);
    }

    /**
     * Creates a new Shop model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return array|string|\yii\web\Response
     * @throws \yii\db\Exception
     */
    public function actionCreate()
    {
        $modelShop = new Shop;
        if ($modelShop->load(Yii::$app->request->post())) {

            $schedulesByWeek = ScheduleByWeek::createMultiple(ScheduleByWeek::class);
            Model::loadMultiple($schedulesByWeek, Yii::$app->request->post());

            // ajax validation
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ArrayHelper::merge(
                    ActiveForm::validateMultiple($schedulesByWeek),
                    ActiveForm::validate($modelShop)
                );
            }

            // validate all models
            $valid = $modelShop->validate();
            $valid = Model::validateMultiple($schedulesByWeek) && $valid;
            if ($valid) {
                if (ScheduleByWeek::saveMultiple($modelShop, $schedulesByWeek, 'shop_id'))
                    return $this->redirect(['view', 'id' => $modelShop->id]);
            }
        }

        return $this->render('create', [
            'daysOfWeek'=>ScheduleByWeek::daysOfWeek(),
            'modelShop' => $modelShop,
            'schedulesByWeek' => (empty($schedulesByWeek)) ? ScheduleByWeek::createModels() : $schedulesByWeek
        ]);
    }

    /**
     * Updates an existing Shop model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     * @throws \yii\db\Exception
     */
    public function actionUpdate($id)
    {
        $modelShop = $this->findModel($id);
        $schedulesByWeek = $modelShop->schedulesByWeek;
        $schedulesByWeek = ScheduleByWeek::createModels($schedulesByWeek, 'update');

        if ($modelShop->load(Yii::$app->request->post())) {

            $schedulesByWeek = ScheduleByWeek::createMultiple(ScheduleByWeek::class, $schedulesByWeek, 'shop_id', $modelShop->id);
            Model::loadMultiple($schedulesByWeek, Yii::$app->request->post());

            // ajax validation
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ArrayHelper::merge(
                    ActiveForm::validateMultiple($schedulesByWeek),
                    ActiveForm::validate($modelShop)
                );
            }

            // validate all models
            $valid = $modelShop->validate();
            $valid = Model::validateMultiple($schedulesByWeek) && $valid;

            if ($valid) {
                if (ScheduleByWeek::saveMultiple($modelShop, $schedulesByWeek, null, 'update',
                    ScheduleByWeek::class))
                    return $this->redirect(['view', 'id' => $modelShop->id]);
            }
        }

        return $this->render('update', [
            'modelShop' => $modelShop,
            'schedulesByWeek' => (empty($schedulesByWeek)) ? [new ScheduleByWeek] : $schedulesByWeek,
            'daysOfWeek'=>ScheduleByWeek::daysOfWeek(),
        ]);

    }

    /**
     * Deletes an existing Shop model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     * @throws \Exception
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Shop model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Shop the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Shop::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

views/shop/_form.php
<?php
/**
 * @var \app\models\ScheduleByWeek[] $schedulesByWeek
 */
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>

<div class="customer-form">

    <?php $form = ActiveForm::begin(['id' => 'dynamic-form', 'enableAjaxValidation' => true]); ?>
    <div class="row">
        <div class="col-sm-6">
            <?= $form->field($modelShop, 'name')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-sm-6">
            <?= $form->field($modelShop, 'description')->textarea(['rows' => 6]) ?>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading"><h4>Schedules by days of week</h4></div>
        <div class="panel-body">
            <div id="schedule-container" class="container-items"><!-- widgetContainer -->
                <?php foreach ($schedulesByWeek as $i => $scheduleByWeek): ?>
                    <div class="item panel panel-default"><!-- widgetBody -->
                        <div class="panel-heading">
                            <h3 class="panel-title pull-left"><?=$daysOfWeek[$i]?></h3>
                            <div class="clearfix"></div>
                        </div>
                        <div class="panel-body schedule-body">
                            <?php
                            // necessary for update action.
                            if (! $scheduleByWeek->isNewRecord) {
                                echo Html::activeHiddenInput($scheduleByWeek, "[{$i}]id");
                            }
                            ?>
                            <?= Html::activeHiddenInput($scheduleByWeek, "[{$i}]day_of_week"); ?>
                            <div class="row">
                                <div class="col-sm-12">
                                    <?= $form->field($scheduleByWeek, "[{$i}]shop_is_closed")->checkbox(['class'=>'close-schedule']) ?>
                                </div>
                            </div>
                            <div class="row shop-time">
                                <div class="col-sm-6">
                                    <?= $form->field($scheduleByWeek, "[{$i}]open_time")->widget(\kartik\time\TimePicker::class, [
                                        'value'=>$scheduleByWeek->open_time?Yii::$app->formatter->asTime($scheduleByWeek->open_time):null,
                                        'options'=>[
                                            'placeholder' => 'Enter schedule time...',
                                            'autocomplete'=>'off',
                                        ],
                                        'pluginOptions' => [
                                            'showMeridian'=>false,
                                            'defaultTime'=>false,
                                        ]
                                    ]) ?>
                                </div>
                                <div class="col-sm-6">
                                    <?= $form->field($scheduleByWeek, "[{$i}]close_time")->widget(\kartik\time\TimePicker::class, [
                                        'value'=>$scheduleByWeek->close_time?Yii::$app->formatter->asTime($scheduleByWeek->close_time):null,
                                        'options'=>[
                                            'placeholder' => 'Enter schedule time...',
                                            'autocomplete'=>'off',
                                        ],
                                        'pluginOptions' => [
                                            'showMeridian'=>false,
                                            'defaultTime'=>false,
                                        ]
                                    ]) ?>
                                </div>
                            </div><!-- .row -->
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>

    <div class="form-group">
        <?= Html::submitButton($modelShop->isNewRecord ? 'Create' : 'Update', ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/shop/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ShopSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="shop-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'description') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/shop/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Shop */

$this->title = Yii::t('app', 'Create Shop');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Shops'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="shop-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'modelShop' => $modelShop,
        'schedulesByWeek' => $schedulesByWeek,
        'daysOfWeek'=>$daysOfWeek,
    ]) ?>

</div>

views/shop/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/shop/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel app\models\ShopSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Shops');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="shop-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('app', 'Create Shop'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'name',
            [
                'attribute'=>'description',
                'format'=>'ntext',
                'enableSorting' => false
            ],
            [
                'attribute'=>'schedule_search',
                'label'=>'Schedule',
                'format'=>'html',
                'value'=>function($model) use ($date){
                    return \app\widgets\ScheduleWidget::widget(['schedule'=>$model->getSchedule($date)]);
                },
                'filter'=>\kartik\date\DatePicker::widget([
                    'model'=>$searchModel,
                    'attribute'=>'schedule_search',
                    'options' => [
                        'autocomplete'=>'off'
                    ],
                    'type'=>\kartik\date\DatePicker::TYPE_INPUT,
                    'pluginOptions' => [
                        'autoclose'=>true,
                        'format'=>'yyyy-mm-dd'
                    ]
                ])
            ],

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
    <?php Pjax::end(); ?>
</div>

views/shop/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Shop */

$this->title = Yii::t('app', 'Update Shop: {nameAttribute}', [
    'nameAttribute' => $model->name,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Shops'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="shop-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'modelShop' => $modelShop,
        'schedulesByWeek' => $schedulesByWeek,
        'daysOfWeek'=>$daysOfWeek,
    ]) ?>

</div>

views/shop/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Shop */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Shops'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="shop-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'name',
            'description:ntext',
            [
                'label'=>'Schedule',
                'format'=>'html',
                'value'=>function($model){
                    return \app\widgets\ScheduleWidget::widget(['schedule'=>$model->schedule]);
                }
            ],
        ],
    ]) ?>
    <?php \yii\widgets\Pjax::begin(['id'=>'date-list']); ?>
    <p>
        <?= Html::a(Yii::t('app', 'Add schedule'), ['schedule/create', 'id' => $model->id], ['class' => 'btn btn-success']) ?>
    </p>
    <h1>Schedule by dates:</h1>
    <?= \yii\grid\GridView::widget([
        'dataProvider' => $scheduleDataProvider,
        'filterModel' => $scheduleSearchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            [
                'attribute'=>'date',
                'filter'=>\kartik\date\DatePicker::widget([
                    'model'=>$scheduleSearchModel,
                    'attribute'=>'date',
                    'options' => [
                        'autocomplete'=>'off'
                    ],
                    'type'=>\kartik\date\DatePicker::TYPE_INPUT,
                    'pluginOptions' => [
                        'autoclose'=>true,
                        'format'=>'yyyy-mm-dd'
                    ]
                ])
            ],
            [
                'attribute'=>'open_time',
                'format'=>'time',
                'filter'=>\kartik\time\TimePicker::widget([
                    'model'=>$scheduleSearchModel,
                    'attribute'=>'open_time',
                    'options' => [
                        'autocomplete'=>'off'
                    ],
                    'pluginOptions' => [
                        'showMeridian'=>false,
                        'defaultTime'=>false,
                    ]
                ])
            ],
            [
                'attribute'=>'close_time',
                'format'=>'time',
                'filter'=>\kartik\time\TimePicker::widget([
                    'model'=>$scheduleSearchModel,
                    'attribute'=>'close_time',
                    'options' => [
                        'autocomplete'=>'off'
                    ],
                    'pluginOptions' => [
                        'showMeridian'=>false,
                        'defaultTime'=>false,
                    ]
                ])
            ],

            [
                'class'    => 'yii\grid\ActionColumn',
                'controller'=>'schedule',
                'template'=>'{update} {delete}',
            ],
        ],
    ]); ?>
    <?php \yii\widgets\Pjax::end(); ?>
</div>